USE SQLCinema;


CALL create_keyword_set('It Lives Inside', 'based on myths, legends or folklore', TRUE);
CALL create_keyword_set('Drifter', 'berlin, germany,gay love', TRUE);
CALL create_keyword_set('Fallen Leaves', 'helsinki, finland,romance,working class people', TRUE);
CALL create_keyword_set('Sometime, Sometime', 'single parent,film in film,family,mom and son', TRUE);
CALL create_keyword_set('Youth Topia', 'underdog,coming of age,youth culture', TRUE);
CALL create_keyword_set('Talk to Me', 'exploitation,addiction,possession,female protagonist,mental health,dead parent,disembodied hand,generation z,supernatural horror,adelaide australia,teenager', TRUE);
CALL create_keyword_set('Theater Camp', 'coma,friendship,camp,improvisation,new york state,woman director,theatre,theater,ensemble', TRUE);
CALL create_keyword_set('Mission: Impossible - Dead Reckoning Part One', 'rome, italy,norway,chase,secret agent,sequel,based on tv series', TRUE);
CALL create_keyword_set('Earth Mama', 'single parent,rehabilitation centre,community,single mother,custody,pregnant woman,motherhood,woman director,foster care,northern california', TRUE);
CALL create_keyword_set('Biosphere', 'human extinction,post apocalypse', TRUE);
CALL create_keyword_set('Miraculous: Ladybug & Cat Noir, The Movie', 'paris, france,superhero,interracial romance,teen superhero', TRUE);
CALL create_keyword_set('Indiana Jones and the Dial of Destiny', 'sequel,knife fight,archaeologist,adventurer,1960s,relic hunter', TRUE);
CALL create_keyword_set('Joy Ride', 'female friendship,adopted child,woman director,asian american', TRUE);
CALL create_keyword_set('John Early: Now More Than Ever', 'stand-up comedy', TRUE);
CALL create_keyword_set('The Blackening', 'cabin,parody,slasher,group of friends,weekend getaway,african american,juneteenth', TRUE);
CALL create_keyword_set('Black Clover: Sword of the Wizard King', 'magic,demon,wizard,shounen,anime,japanese', TRUE);
CALL create_keyword_set('The Glassworker', 'letter,anime', TRUE);
CALL create_keyword_set('Anthropophagus II', 'splatter film,cannibal cult', TRUE);
CALL create_keyword_set('Elemental', 'fire,computer animation,elements,water,city', TRUE);
CALL create_keyword_set('The Flash', 'secret identity,hero,superhero,based on comic,superhuman,super power,butterfly effect,dc extended universe (dceu),superhuman abilities', TRUE);
CALL create_keyword_set('Asteroid City', 'space,alien,astronomy,1950s,convention,desert town', TRUE);
CALL create_keyword_set('Medusa Deluxe', 'competition,whodunit,single take,murder mystery,hairdressing', TRUE);
CALL create_keyword_set('Transformers: Rise of the Beasts', 'alien,end of the world,based on cartoon,based on toy,robot,1990s', TRUE);
CALL create_keyword_set('Travelers', 'immigrant,u.s. navy,home movie footage,undocumented immigrant,seaman,filipino american,san pablo city,dennis empalmado,filipino,filipino in usa,filipino abroad,naglalakbay,travelers,pleasant dreams production,ucla professor,cafe owner,tnt', TRUE);
CALL create_keyword_set('Monster', 'kids', TRUE);
CALL create_keyword_set('Reality', 'fbi,georgia,based on true story,based on play or musical,information leak,veteran,questioning,2010s', TRUE);
CALL create_keyword_set('Past Lives', 'new york city,regret,immigrant,friendship,interracial relationship,fate,childhood,childhood friends,woman director,korean american,korean,asian american', TRUE);
CALL create_keyword_set('A Beautiful Life', 'fisherman,singer', TRUE);
CALL create_keyword_set('It’s Nice in Here', 'short film', TRUE);
CALL create_keyword_set('The Boogeyman', 'based on novel or book', TRUE);
CALL create_keyword_set('The Roommate', 'short film,student film,film,comedy,drama', TRUE);
CALL create_keyword_set('Spider-Man: Across the Spider-Verse', 'sequel,superhero,based on comic,multiverse,alternate universe', TRUE);
CALL create_keyword_set('Mojave Diamonds', 'kidnapping,las vegas,underground fighting,stolen truck,truck driver,diamonds,protective brothers,brothers,mma,stolen diamonds', TRUE);
CALL create_keyword_set('Anhell69', 'radical,death,queer,experimental', TRUE);
CALL create_keyword_set('The Wrath of Becky', 'sequel,murder,gore', TRUE);
CALL create_keyword_set('Strange Way of Life', 'lgbt,almería, spain,short film,gay,gay character,cannes official selection', TRUE);
CALL create_keyword_set('You Hurt My Feelings', 'new york city,husband wife relationship,novelist,woman director,criticism', TRUE);
CALL create_keyword_set('Cobweb', '1970s,film in film,censorship,portrait of a filmmaker,experimental', TRUE);
CALL create_keyword_set('About My Father', 'father son conflict', TRUE);
CALL create_keyword_set('Adam & Henry Adventures', 'travel,coming of age,docudrama,documentary filmmaking,portrait of a filmmaker,bikepacking,eurotrip', TRUE);
CALL create_keyword_set('Master Gardener', 'garden,character study', TRUE);
CALL create_keyword_set('Robots', 'romantic comedy,robot,scam artist,independent film,dating scam', TRUE);
CALL create_keyword_set('Dalíland', 'salvador dalí,art,biopic', TRUE);
CALL create_keyword_set('Anwar: The Untold Story', 'biography,1990s', TRUE);
CALL create_keyword_set('The Little Mermaid', 'musical,mermaid,based on fairy tale,live action remake', TRUE);
CALL create_keyword_set('Fanfic', 'transsexuality,lgbt,gay theme,gay', TRUE);
CALL create_keyword_set('Fast X', 'sequel,racing,family', TRUE);
CALL create_keyword_set('Who Wants to Be Your Friend When Your Star Fades', 'musical,football (soccer) coach,football', TRUE);
CALL create_keyword_set('Bless Me Father', 'new jersey,italian american,confession,gangster,strip club,mafia,mobster,church,roman catholic,mob,wise guy,italian neo realism,riveting,thriller,action,movie,bless me father', TRUE);
CALL create_keyword_set('Talking To Ghosts', 'revenge,tragedy,miscarriage,heartbreak,gun dealer,abortion,talking to ghosts', TRUE);
CALL create_keyword_set('Subspecies V: Blood Rise', 'transylvania,coffin,vampire,serbia,vampire hunter (slayer),prequel,bucharest, romania,haunted castle,belgrade,stake,human vampire relationship,origin story,monster hunter', TRUE);
CALL create_keyword_set('Dream Moms', 'musical', TRUE);
CALL create_keyword_set('Fall Guy', 'innocence', TRUE);
CALL create_keyword_set('Phalguna Chaitra', 'village life,family', TRUE);
CALL create_keyword_set('Rally Road Racers', 'bet,car race,grandmother,cup,betting,race car driver,rally,grandmother grandson relationship,grandma,race car driving,speed racing,animation,car racing,american animation,making a bet', TRUE);
CALL create_keyword_set('The Starling Girl', 'christianity,dance,sin,coming of age,religion,love affair,alcoholic father,woman director,shame,father daughter relationship,mother daughter relationship,expression,youth pastor', TRUE);
CALL create_keyword_set('Fatafati', 'body shaming', TRUE);
CALL create_keyword_set('Crater', 'road trip,coming of age,group of friends,moon colony,near future', TRUE);
CALL create_keyword_set('Monica', 'forgiveness,dying mother,lgbt,acceptance,mother daughter relationship,transgender', TRUE);
CALL create_keyword_set('Royalteen: Princess Margrethe', 'based on novel or book,sequel,woman director,oslo, norway', TRUE);
CALL create_keyword_set('BlackBerry', 'silicon valley,biography,rise and fall,phone,smartphone', TRUE);
CALL create_keyword_set('White Men Can t Jump', 'basketball', TRUE);
CALL create_keyword_set('Hello Ghost', 'suicide,remake,ghost', TRUE);
CALL create_keyword_set('Hypnotic', 'duringcreditsstinger,missing daughter', TRUE);
CALL create_keyword_set('Streamer', 'paranormal investigation,found footage,live stream,abandoned building,screenlife', TRUE);
CALL create_keyword_set('War Pony', 'halloween,thanksgiving,turkey,poodle,coming of age,native american reservation,lakota,bison', TRUE);
CALL create_keyword_set('Hurry Up & Wait', 'stress,revenge,rush,dark,thriller,drama,hurry', TRUE);
CALL create_keyword_set('Hannah Gadsby: Something Special', 'stand-up comedy', TRUE);
CALL create_keyword_set('ROB.B', 'robot,short film,science fiction,comedy', TRUE);
CALL create_keyword_set('Paraffin', 'fight,drugs,gross out,lava lamp,comedy', TRUE);
CALL create_keyword_set('Boys on the Bridge', 'friendship,coming of age,boys', TRUE);
CALL create_keyword_set('Fragile and Damaged', 'relationship problems,domestic abuse,parenting,moody,avoidant,emotionally blocked,altruistic', TRUE);
CALL create_keyword_set('Jackson Halt', 'railway station,mysterious events,thriller,maithili,mithilanchal,maithili film', TRUE);
CALL create_keyword_set('24 Tears Per Second', 'mockumentary,noir,the office', TRUE);
CALL create_keyword_set('Seanestro Bernal s Veil', 'martial arts,assassin,police,superhero,mixed martial arts,character study,neo-noir,dark,stealth slasher', TRUE);
CALL create_keyword_set('Ip Man: The Awakening', 'martial arts,kung fu,hong kong,wing chun', TRUE);
CALL create_keyword_set('Tommy Little: Pretty Fly for A Dickhead', 'stand-up comedy,comedy', TRUE);
CALL create_keyword_set('Maggie Simpson in "Rogue Not Quite One"', 'based on tv series', TRUE);
CALL create_keyword_set('The Adventures of Jurassic Pet 2: The Lost Secret', 'dinosaur', TRUE);
CALL create_keyword_set('Love Again', 'based on novel or book,text message,duringcreditsstinger', TRUE);
CALL create_keyword_set('The Mother', 'female assassin,woman director,mother and daughter', TRUE);
CALL create_keyword_set('Sunsets at Noon', 'e-comm', TRUE);
CALL create_keyword_set('Guardians of the Galaxy Vol. 3', 'hero,sequel,superhero,based on comic,mad scientist,superhero team,space opera,raccoon,aftercreditsstinger,duringcreditsstinger,marvel cinematic universe (mcu),cosmic,outer space,chosen family', TRUE);
CALL create_keyword_set('Lewis Black: Tragically, I Need You', 'stand-up comedy,observational comedy,comedy routine,stand-up,comedy', TRUE);
CALL create_keyword_set('Caviar', 'found footage,political satire', TRUE);
CALL create_keyword_set('Jimmy O. Yang: Guess How Much?', 'stand-up comedy', TRUE);
CALL create_keyword_set('Grape Soda in the Parking Lot', 'indigenous,inuit,language,oil painting', TRUE);
CALL create_keyword_set('Andy & Lucy Watch TV', 'sitcom,meta,tv', TRUE);
CALL create_keyword_set('Giving Birth to a Butterfly', 'surrealism', TRUE);
CALL create_keyword_set('The Bitter', 'short film,student film', TRUE);
CALL create_keyword_set('Where the Cattle Laid', 'short film,student film', TRUE);
CALL create_keyword_set('The Last Revelry', 'short film,student film', TRUE);
CALL create_keyword_set('It s All True', 'musical,romance,storytelling,mental health,album,visual album,lesbian,lgbtq+,indie', TRUE);
CALL create_keyword_set('Heavy Snow', 'coming of age,lgbt teen,lesbian', TRUE);
CALL create_keyword_set('Pamir', 'sewol,based on short film', TRUE);
CALL create_keyword_set('Snag', 'gangsters', TRUE);
CALL create_keyword_set('A Bear Named Jesus', 'indigenous,religion,mourning', TRUE);
CALL create_keyword_set('Kill Her Goats', 'psychopath,murder,serial killer,goat,slasher', TRUE);
CALL create_keyword_set('Durham Place', 'house,money,heist gone wrong,heist thriller', TRUE);
CALL create_keyword_set('Vikings: Battle of Heirs', 'viking', TRUE);
CALL create_keyword_set('Born to Fly', 'fighter pilot,fighter jet,military life', TRUE);
CALL create_keyword_set('Nobody Meets Your Eyes', 'loneliness,invisible person', TRUE);
CALL create_keyword_set('U-Turn', 'remake', TRUE);
CALL create_keyword_set('Big Shark', 'new orleans, louisiana,shark,campy,horror comedy,firemen,independent film,low budget', TRUE);
CALL create_keyword_set('Sid is Dead', 'high school,teen comedy,school suspension,bucket list,school bully', TRUE);
CALL create_keyword_set('false prophets', 'false prophets', TRUE);
CALL create_keyword_set('An Egypt Affair', 'seduction,ancient egypt,betrayal by friend,yolanthe cabau', TRUE);
CALL create_keyword_set('Vamos a la playa', 'road movie,sex tourism', TRUE);
CALL create_keyword_set('Bezos', 'based on true story,jeff bezos,amazon company', TRUE);
CALL create_keyword_set('Polite Society', 'martial arts,kidnapping,wedding,woman director,sister sister relationship', TRUE);
CALL create_keyword_set('What the Waters Left Behind: Scars', 'kidnapping,gore,rock band', TRUE);
CALL create_keyword_set('99 Moons', 'swinger club,love affair,witness to a crime,acid trip', TRUE);
CALL create_keyword_set('Big George Foreman', 'adultery,1970s,texas,biography,family,1980s,1960s,boxing', TRUE);
CALL create_keyword_set('Are You There God? It s Me, Margaret.', 'new jersey,adolescence,based on novel or book,puberty,coming of age,religion,woman director,mother daughter relationship', TRUE);
CALL create_keyword_set('Knights of the Zodiac', 'superhero,based on manga,live action anime', TRUE);
CALL create_keyword_set('Woodsman', 'dance,forest,marriage,woods,tragic hero,ballet,psychological thriller,illness,resentment,tragic romance,communication,modern fairy tale,thriller', TRUE);
CALL create_keyword_set('The Black Demon', 'shark attack,shark,killer shark,oil rig ,oilman,sharksploitation', TRUE);
CALL create_keyword_set('Dream', 'sports,football (soccer),football (soccer) team', TRUE);
CALL create_keyword_set('The Boulet Brothers  Halfway to Halloween TV Special', 'drag queen,halloween,sketch comedy,variety special', TRUE);
CALL create_keyword_set('Justice League x RWBY: Super Heroes & Huntsmen, Part One', 'based on comic,rwby', TRUE);
CALL create_keyword_set('Daytripper', 'male ballet dancer', TRUE);
CALL create_keyword_set('The Elevator', 'haunted hotel', TRUE);
CALL create_keyword_set('The Day I Realized I’m in Love', 'short film,web movie', TRUE);
CALL create_keyword_set('Secrets on Greek Row', 'college,whodunit,killer,young adult,lies,mystery', TRUE);
CALL create_keyword_set('Heartbreakers', 'revenge,slasher,summer vacation,teen comedy,teenage killer,blood,teenager,teen horror', TRUE);
CALL create_keyword_set('War of the Worlds: The Attack', 'planet mars,space war,evil alien,planet invasion,alien conspiracy,war of the worlds', TRUE);
CALL create_keyword_set('Blood & Gold', 'world war ii', TRUE);
CALL create_keyword_set('20,000 Species of Bees', 'trans', TRUE);
CALL create_keyword_set('Viking: Bloodlust', 'viking', TRUE);
CALL create_keyword_set('Kindling', 'friendship,teenage romance,teen drama', TRUE);
CALL create_keyword_set('Carmen', 'based on novel or book,usa–mexico border', TRUE);
CALL create_keyword_set('Soltera, casada, viuda, divorciada', 'aging,female friendship,road trip,death in family,motherhood,grieving widow', TRUE);
CALL create_keyword_set('National Theatre Live: Good', 'germany,world war ii,professor,wartime,stage play,live play,live theatre,jewish history,war,jewish,jews,nazi germany,second war,good and evil', TRUE);
CALL create_keyword_set('Afire', 'summer,forest fire', TRUE);
CALL create_keyword_set('The Challenge', 'space mission,iss,international space station', TRUE);
CALL create_keyword_set('Kawa', 'scientist,indigenous community', TRUE);
CALL create_keyword_set('The New Order', 'revolution,secret society', TRUE);
CALL create_keyword_set('Peter Pan & Wendy', 'island,magic,fairy,fairy tale,peter pan,immortality,remake,pirate,based on children s book,fantasy world,live action remake', TRUE);
CALL create_keyword_set('Pretty Stoned', 'drug dealer', TRUE);
CALL create_keyword_set('Mighty Morphin Power Rangers: Once & Always', 'hero,superhero,superhero team,masked superhero,anniversary,aging superhero,based on tv series,female superhero,sentai', TRUE);
CALL create_keyword_set('Guy Ritchie s The Covenant', 'ambush,interpreter,afghanistan,afghanistan war (2001- ),rescue,war', TRUE);
CALL create_keyword_set('Money Talk', 'drug crime,high school,stolen money,dark comedy,money,drugs,high school friends,witness to a crime,paranoid thriller,modern-day thriller,drug,chase scenes,black comedy,crime,comedy', TRUE);
CALL create_keyword_set('The Astral Woods', 'extraterrestrial,cabin in the woods', TRUE);
CALL create_keyword_set('Nightmare Radio: The Night Stalker', 'radio station,stalker,horror anthology', TRUE);
CALL create_keyword_set('Ghosted', 'secret agent', TRUE);
CALL create_keyword_set('Tight Pants Ultra Bold', 'skateboarding,failure,earth,collage,y2k,stop motion,bathtub,internet culture,font,creative process,1990s,graphic design,cutout animation,typography,collage film,typing,vlogger,2000s,stop frame,energy drink,cut-out,early internet,geocities,font design,1996,papa s free font bucket', TRUE);
CALL create_keyword_set('Regarding Eloise', 'allegory,dangerous,moral conflict,mental illness,old house,yelling,graveyard,vintage,lonely woman,friendship between women,skeletons,all female', TRUE);
CALL create_keyword_set('Paper Planes', 'agoraphobia,christmas,lgbtq', TRUE);
CALL create_keyword_set('Queens on the Run', 'fight,road trip,female protagonist,encounter group', TRUE);
CALL create_keyword_set('Phenomena', 'madrid, spain,medium,female friendship,based on true story,catholic priest,paranormal activity,1990s,paranormal investigator', TRUE);
CALL create_keyword_set('Sweetwater', 'basketball,nba,1950s', TRUE);
CALL create_keyword_set('The Last Kingdom: Seven Kings Must Die', 'fight,kingdom,battle for power,heir to the throne,crown,king,battle,death of king,invaders,heirs', TRUE);
CALL create_keyword_set('Nefarious', 'evangelical,psychiatrist,evangelical christianity,demonic possession,psychological terror,christian', TRUE);
CALL create_keyword_set('Beau Is Afraid', 'suicide,paranoia,therapist,trauma,nightmare,orgasm,childhood trauma,satire,grief,surrealism,crude humor,dark comedy,fear,maniac,birth,attic,death of mother,entrepreneur,existentialism,anxiety disorder,absurdist,mother son relationship,based on short film,anxiety,bizarre comedy,odyssey', TRUE);
CALL create_keyword_set('Killing Romance', 'pacific,south pacific,actress', TRUE);
CALL create_keyword_set('Mafia Mamma', 'italy,mafia,camp,woman director', TRUE);
CALL create_keyword_set('in water', 'jeju island', TRUE);
CALL create_keyword_set('Evil Dead Rise', 'sibling relationship,earthquake,pregnancy,sequel,gore,los angeles, california,demon,evil,necronomicon,reboot,demonic possession,motherhood,sisterhood,sister sister relationship,body horror,apartment,graphic violence', TRUE);
CALL create_keyword_set('Faces of Horror Part II', 'documentary filmmaking,documentary film', TRUE);
CALL create_keyword_set('Spectre: Genesis', 'anti hero,superhero,revenge plot,teen superhero', TRUE);
CALL create_keyword_set('The Perfect Stranger', 'subway,stalker,mall,subway station,following,eerie,toronto', TRUE);
CALL create_keyword_set('Honto ni Atta! Noroi no Video 101', 'psychic phenomena,screenlife', TRUE);
CALL create_keyword_set('La Usurpadora: The Musical', 'musical,dual role,twins separated at birth,telenovela,identical twin,musical adaptation', TRUE);
CALL create_keyword_set('Delivery Boy', 'ollywood', TRUE);
CALL create_keyword_set('My Beautiful Man ～eternal～', 'based on novel or book,lgbt,gay romance,boys  love (bl)', TRUE);
CALL create_keyword_set('Summoning Sylvia', 'haunted house,ghost,horror comedy,bachelor party,lgbtq+', TRUE);
CALL create_keyword_set('How to Blow Up a Pipeline', 'bomb,based on novel or book,winter,texas,climate change,terminal illness,flashback,informant,radical,eco terrorism,lgbt,enviroment,activist,activism,environmental activist,environmental issues,pipeline', TRUE);
CALL create_keyword_set('Oh Belinda', 'remake,tv commercial,dimensional travel,interdimensional travel', TRUE);
CALL create_keyword_set('Soft', 'lgbt', TRUE);
CALL create_keyword_set('Gumraah', 'remake,based on movie', TRUE);
CALL create_keyword_set('LOLA', 'time travel,found footage', TRUE);
CALL create_keyword_set('One True Loves', 'husband wife relationship,widow,engagement,accident,back to life,best friends,bookstore', TRUE);
CALL create_keyword_set('Showing Up', 'portland, oregon,artist,landlord,art,sculptor,woman director,art exhibition', TRUE);
CALL create_keyword_set('Chupa', 'legend,urban legend,coming of age,mexican legend,chupacabra', TRUE);
CALL create_keyword_set('Renfield', 'vampire,police,gore,bugs,mob family,crooked cops,immortal,dracula,abusive relationship,bloody death,violence', TRUE);
CALL create_keyword_set('Praise This', 'gospel,church,singing competition,gospel music,music', TRUE);
CALL create_keyword_set('Home for Rent', 'ritual murder,satanic cult', TRUE);
CALL create_keyword_set('On a Wing and a Prayer', 'airplane,based on true story,family,duringcreditsstinger', TRUE);
CALL create_keyword_set('Sanctuary', 'eroticism,dominatrix,dark comedy,dominance,job promotion,one location,power dynamics', TRUE);
CALL create_keyword_set('Paint', 'painter,insecurity,duringcreditsstinger,local television', TRUE);
CALL create_keyword_set('Chevalier', 'biography,violinist,based on true story', TRUE);
CALL create_keyword_set('Psychic Manjara 39', 'found footage,psychic phenomena', TRUE);
CALL create_keyword_set('Air', 'sports,basketball,based on true story,duringcreditsstinger,1980s', TRUE);
CALL create_keyword_set('Rebound', 'basketball,high school sports,based on true story,busan, south korea,2010s', TRUE);
CALL create_keyword_set('The Three Musketeers: D Artagnan', 'sword,musketeer', TRUE);
CALL create_keyword_set('The Pope s Exorcist', 'spain,rome, italy,vatican,pope,pig,possession,conspiracy,devil,exorcist,skepticism,catholic priest,1980s,supernatural horror', TRUE);
CALL create_keyword_set('The Super Mario Bros. Movie', 'video game,plumber,magic mushroom,based on video game,aftercreditsstinger,duringcreditsstinger,damsel in distress,brother brother relationship', TRUE);
CALL create_keyword_set('Hunger', 'chef,fine dining,cuisine', TRUE);
CALL create_keyword_set('Fist of the Condor', 'martial arts,biker', TRUE);
CALL create_keyword_set('In the Valley of the Moon', 'assassin,italian,1970s,hitman,mafia,mobster,italian filmmaker', TRUE);
CALL create_keyword_set('The Greatest Surf Movie in the Universe', 'surfing,stop motion,cult film,virus,post apocalypse', TRUE);
CALL create_keyword_set('A Tour Guide', 'north korean defector', TRUE);
CALL create_keyword_set('Surrounded', 'civil war,gold mine,frontier,outlaw,stagecoach,buffalo soldier', TRUE);
CALL create_keyword_set('Journey to the West', 'science fiction', TRUE);
CALL create_keyword_set('Hachiko', 'dog,family,hachiko', TRUE);
CALL create_keyword_set('Óráð', 'witch,witchcraft,haunted', TRUE);
CALL create_keyword_set('Trinket Box', 'marriage,love,interracial relationship,evil,paranormal activity', TRUE);
CALL create_keyword_set('RUN', 'clone,chase,escape,time loop,cabin in the woods', TRUE);
CALL create_keyword_set('The Unheard', 'psychological thriller,deaf girl', TRUE);
CALL create_keyword_set('Murderbot', 'killer robot', TRUE);
CALL create_keyword_set('Jawanum Mullappoovum', 'malayalam,shivada', TRUE);
CALL create_keyword_set('Capsules', 'drug abuse,drug scene,coming of age,drug humor,science fiction', TRUE);
CALL create_keyword_set('Acidman', 'estranged father,father daughter relationship', TRUE);
CALL create_keyword_set('A Thousand and One', 'new york city,parent child relationship,convicted felon,woman director,felon,1990s,mother son relationship', TRUE);
CALL create_keyword_set('Space Oddity', 'planet mars,falling in love,woman director,space exploration,space program,social experiment', TRUE);
CALL create_keyword_set('When Time Got Louder', 'autism', TRUE);
CALL create_keyword_set('Spinning Gold', '1970s,jazz,rhythm and blues,disco,singer-songwriter,1980s,1960s,record industry,music industry,r&b artist,biopic,casablanca records', TRUE);
CALL create_keyword_set('Rahul Talks to People', 'stand-up comedy,stand-up,crowdwork', TRUE);
CALL create_keyword_set('Sisi & I', 'austria,biography,historical figure,royalty,empress,period drama,austria-hungary,habsburger,empress elisabeth of austria', TRUE);
CALL create_keyword_set('His Only Son', 'sacrifice,bible,son,father,faith,god,abraham,independent film,biblical,crowd funded', TRUE);
CALL create_keyword_set('Heaven Under The Sky', 'coming of age', TRUE);
CALL create_keyword_set('White Plastic Sky', 'woman director', TRUE);
CALL create_keyword_set('The Veteran', 'war veteran,brother,death,councilor', TRUE);
CALL create_keyword_set('Simulant', 'artificial intelligence,android,synthetic human,synth,turing test,human android relationship,malfunctioning android', TRUE);
CALL create_keyword_set('Mae Martin: SAP', 'stand-up comedy,gender,lgbt', TRUE);
CALL create_keyword_set('Clock', 'woman director,biological clock,clinical trials,psychological horror', TRUE);
CALL create_keyword_set('Heathers: The Musical', 'suicide,ohio,funeral,bullying,paternalism,sociopath,dark comedy,male homosexuality,based on play or musical,coming of age,bomb planting,suicide note,teenage rebellion,based on movie,peer pressure,murdered teen,1980s,teen social issues,filmed play,80s style,closeted homosexual,toxic masculinity,west end,comedy thriller', TRUE);
CALL create_keyword_set('Murder Mystery 2', 'kidnapping,married couple,whodunit,wedding,detective couple', TRUE);
CALL create_keyword_set('Spuria', 'psychological thriller,mysterious stranger', TRUE);
CALL create_keyword_set('Madeleine', 'immigrant,road trip,retirement home', TRUE);
CALL create_keyword_set('Every Breath She Takes', 'fire,house fire,fake death,physical abuse,husband,abuse,abusive husband,spousal abuse', TRUE);
CALL create_keyword_set('The Might of the Daleks', 'fan film,short film,doctor who,daleks,pastiche', TRUE);
CALL create_keyword_set('Ape vs. Mecha Ape', 'monster,sequel,mecha,giant robot,giant monster,kaiju,giant ape', TRUE);
CALL create_keyword_set('Twisted Sister', 'sister,betrayal,trust,family,half sister,betrayal of trust', TRUE);
CALL create_keyword_set('Jacir', 'refugee,memphis, tennessee,independence,politics,poverty,social injustice,syrian refugee', TRUE);
CALL create_keyword_set('The Tutor', 'tutor,manor,persona,secrets', TRUE);
CALL create_keyword_set('The Cow Who Sang a Song into the Future', 'motorcycle,polluted river,grandmother,cow', TRUE);
CALL create_keyword_set('You Can Live Forever', 'love,lgbt,jehovah s witness,homosexuality', TRUE);
CALL create_keyword_set('Yellowbird', 'immigration,animation', TRUE);
CALL create_keyword_set('Moon Trace', 'the rebels productions,moon trace,yousof rafizadeh,رد ماه', TRUE);
CALL create_keyword_set('Sharp Instinct', 'dark comedy,action comedy,detective comedy,greenock,violent,scottish comedy', TRUE);
CALL create_keyword_set('Bank of Dave', 'based on true story,crooked banker,biopic', TRUE);
CALL create_keyword_set('The Portable Door', 'aftercreditsstinger', TRUE);
CALL create_keyword_set('A Good Person', 'vietnam veteran,drug addiction,brother-in-law,fiancé,trauma,forgiveness,father-in-law,ex fiancé,addiction,whiskey,grief,singing,orphan,football (soccer),car accident,sex talk,death,teenage sexuality,haircut,sister-in-law,prescription drug abuse,piano,model train,addiction recovery,retired policeman,ptsd', TRUE);
CALL create_keyword_set('Broken Keys', 'based on true story,religious fundamentalism,sharia law,isis (daesh),syrian refugee,male pianist,syrian civil war,political persecution,based on short film', TRUE);
CALL create_keyword_set('Nothing Like Paris', 'painter as artist,paris', TRUE);
CALL create_keyword_set('Dungeons & Dragons: Honor Among Thieves', 'platonic love,gang of thieves,role playing game,based on video game,dungeons and dragons,heist gone wrong,duringcreditsstinger,father daughter relationship,spell & sorcery,wizardry', TRUE);
CALL create_keyword_set('John Wick: Chapter 4', 'new york city,martial arts,hitman,sequel,organized crime,osaka, japan,aftercreditsstinger,hunted,professional assassin,neo-noir,berlin', TRUE);
CALL create_keyword_set('We Lost Our Human', 'cat,dog,animal,interactive,pet owner,tv special', TRUE);
CALL create_keyword_set('Intruder', 'break in,short film', TRUE);
CALL create_keyword_set('The Hillsdale Adoption Scam', 'adoption,scandal,shady,shady lady,sketchy', TRUE);
CALL create_keyword_set('The Last Page', 'book of mormon', TRUE);
CALL create_keyword_set('Making Him Famous', 'faith,family,christian faith,inspirational film', TRUE);
CALL create_keyword_set('Noise', 'investigation,pandora s box,family drama,dark secret', TRUE);
CALL create_keyword_set('Rye Lane', 'london, england,karaoke,ex-boyfriend,ex-girlfriend,break-up,costume designer,woman director,peckham,accountant,south london,art exhibition', TRUE);
CALL create_keyword_set('Riceboy Sleeps', 'immigrant,coming of age,racism,1990s,mother son relationship,korean,korean canadian', TRUE);
CALL create_keyword_set('Allelujah', 'gay character', TRUE);
CALL create_keyword_set('Boston Strangler', 'journalism,boston, massachusetts,based on true story,serial killer,true crime,investigative journalism,1960s', TRUE);
CALL create_keyword_set('Pinball: The Man Who Saved the Game', 'new york city,california,chicago, illinois,new jersey,bookshop,pinball,breaking the fourth wall,writer,single mother,pinball machine,illegal gambling,duringcreditsstinger,moustache,divorced man', TRUE);
CALL create_keyword_set('Shin Kamen Rider', 'secret organization,superhero,based on manga,motorcycle,reboot,masked superhero,body modification,japanese cinema,based on tv series,mysterious disappearance,body horror', TRUE);
CALL create_keyword_set('Last Sentinel', 'science fact,science fiction,dystopian society,colony sci-fi,military sci-fi,apocalyptic sci-fi', TRUE);
CALL create_keyword_set('Nimmo: Legacy', 'baseball,legacy,mlb,biopic,nimmo', TRUE);
CALL create_keyword_set('Spring Break Nightmare', 'gambling,surfer,kidnapping,gambling debt,surfing,vacation,spring break,female surfer,trip,kidnapped', TRUE);
CALL create_keyword_set('Sea Monsters', 'fish', TRUE);
CALL create_keyword_set('Faith', 'short film', TRUE);
CALL create_keyword_set('Your Move', 'gun,gang leader,gang,police chase,cigar smoking,period drama,gang member,gunshot,killed,1960s,cigarette girl,murder by gunshot,cigar smoker,fast car,period,period film,period piece,smuggling,cigarette smoking,car', TRUE);
CALL create_keyword_set('Tetris', 'video game,cold war,nintendo,based on true story,salesman,duringcreditsstinger,1980s,russia', TRUE);
CALL create_keyword_set('Soulmate', 'soulmates,female friendship,remake,romance,korean', TRUE);
CALL create_keyword_set('Shazam! Fury of the Gods', 'superhero,end of the world,super power,aftercreditsstinger,duringcreditsstinger,dc extended universe (dceu),teenager', TRUE);
CALL create_keyword_set('Bert Kreischer: Razzle Dazzle', 'stand-up comedy', TRUE);
CALL create_keyword_set('Plastic Girl', 'trauma,surreal,thailand,interview,surrealism,thai,death,female writer,short film,biblical reference', TRUE);
CALL create_keyword_set('Little Bone Lodge', 'scotland,mother,lodge,brother,family secrets,hostage-taking,family clan,fugitive,storm,criminal,held captive,family in peril,isolated farmhouse,stormy night,dark secret,highlands,matriarch,scottish highlands', TRUE);
CALL create_keyword_set('Flamin  Hot', 'biography,based on true story,janitor,mexican american,woman director', TRUE);
CALL create_keyword_set('SSSS.Dynazenon Movie', 'mecha,giant robot,giant monster,compilation,kaiju,anime,robot dinosaur', TRUE);
CALL create_keyword_set('Batman: The Doom That Came to Gotham', 'cult,superhero,based on comic,mad doctor,demon,supernatural creature,explorer,masked vigilante,masked superhero,ancient evil,magic book', TRUE);
CALL create_keyword_set('I Like Movies', 'canada,male friendship,friendship,high school,film in film,grief,teen angst,suburbia,suburb,ontario, canada,teenage boy,video store,teen comedy,suburban angst,home movies,canadian youth,youth comedy,2000s,creativity,canadian cinema,anxiety,period piece,burlington,teenage friendship,best friends', TRUE);
CALL create_keyword_set('Therapy Dogs', 'male friendship,friendship,high school,coming of age,high school friends', TRUE);
CALL create_keyword_set('Southern Gospel', 'based on true story', TRUE);
CALL create_keyword_set('The Magician s Elephant', 'elephant,search', TRUE);
CALL create_keyword_set('Inside', 'thief,art thief,art,trapped,trapped in a house,smart home,one location,art heist,security camera,new york', TRUE);
CALL create_keyword_set('Champions', 'basketball,special olympics,basketball team,aftercreditsstinger,duringcreditsstinger,special needs,basketball coach', TRUE);
CALL create_keyword_set('The Ritual Killer', 'black magic,serial killer', TRUE);
CALL create_keyword_set('Portrait of a Killer', '1970s,serial killer,portrait', TRUE);
CALL create_keyword_set('Scream VI', 'new york city,mask,trauma,halloween,college,fake identity,sequel,revenge,public murder,murder,gore,serial killer,conspiracy theory,social commentary,police corruption,slasher,whodunit,multiple stabbings,brutality,killing spree,self-referential,crime spree,aftercreditsstinger,sisterhood,movie fan,copycat killer,masked villain,stabbed to death,sister sister relationship,fbi agent,post credit scene,masked killer', TRUE);
CALL create_keyword_set('Ghost Webcam', 'found footage', TRUE);
CALL create_keyword_set('Psychic Manjara 38', 'psychic phenomena', TRUE);
CALL create_keyword_set('Ohio Walnuts', 'rap music,documentary,music', TRUE);
CALL create_keyword_set('Aprilis', 'death through the camera lens,white flowers', TRUE);
CALL create_keyword_set('The Guest', 'psychological thriller,dinner,short film,secret', TRUE);
CALL create_keyword_set('Doraemon: Nobita s Sky Utopia', 'anime', TRUE);
CALL create_keyword_set('Gulmohar', 'dysfunctional family', TRUE);
CALL create_keyword_set('The Year Between', 'mental illness,woman director,bipolar disorder,late coming of age,college dropout', TRUE);
CALL create_keyword_set('Palm Trees and Power Lines', 'coming of age,woman director,based on short film', TRUE);
CALL create_keyword_set('Behind the Scenes: I ve Been Here Alone', 'infertility,psychological thriller,marriage problems', TRUE);
CALL create_keyword_set('Silent Witnesses', 'collage,silent,colombian', TRUE);
CALL create_keyword_set('Silver Haze', 'lgbt,east london', TRUE);
CALL create_keyword_set('65', 'monster,asteroid,cave,giant monster,dinosaur,quicksand,crash landing,alien race,sick child,prehistoric adventure,prehistoric times,shipwrecked,prehistory,man vs nature,father daughter relationship,alien spaceship', TRUE);
CALL create_keyword_set('Virgo and the Sparklings', 'teen superhero,bumi langit,jagat sinema bumilangit', TRUE);
CALL create_keyword_set('Mavka: The Forest Song', 'based on novel or book,fairy,nature,folklore,based on myths, legends or folklore,mavka,ukrainian folklore', TRUE);
CALL create_keyword_set('Present', 'cold,family drama,black and white,death,political,emotional', TRUE);
CALL create_keyword_set('Horror in the High Desert 2: Minerva', 'mockumentary,missing person,found footage,mysterious disappearance', TRUE);
CALL create_keyword_set('Tonight You re Sleeping with Me', 'infidelity,love,romance', TRUE);
CALL create_keyword_set('Old Flame', 'ex-boyfriend,ex-girlfriend,ex-lover,psychological thriller,cat and mouse,kinky,ex-boyfriend ex-girlfriend relationship,college reunion,two-hander,suspense', TRUE);
CALL create_keyword_set('Craving', 'gore,creature feature,monster movie,drug addict', TRUE);
CALL create_keyword_set('Egghead & Twinkie', 'coming out,coming of age,lgbt teen', TRUE);
CALL create_keyword_set('Creed III', 'philadelphia, pennsylvania,husband wife relationship,deaf,sports,sequel,orphan,former best friend,ex-con,childhood friends,juvenile detention center,boxing,prodigy', TRUE);
CALL create_keyword_set('The Devil s Deal', '1990s,busan, south korea', TRUE);
CALL create_keyword_set('Darienne Lake: Altered Boy', 'drag queen,stand-up comedy,drag,drag race,stand-up', TRUE);
CALL create_keyword_set('Colors', 'stop motion,experimental', TRUE);
CALL create_keyword_set('Cade: The Tortured Crossing', 'artificial intelligence,virtual reality,metaverse', TRUE);
CALL create_keyword_set('There Are Mermaids in LA', 'mermaid,los angeles, california,short film', TRUE);
CALL create_keyword_set('Swipe Right', 'psychological thriller,swipe right', TRUE);
CALL create_keyword_set('Assassin Club', 'assassin,agent,killers,kill', TRUE);
CALL create_keyword_set('We Have a Ghost', 'cia,haunted house,ghost,social media', TRUE);
CALL create_keyword_set('Luther: The Fallen Sun', 'london, england,prison,detective,kidnapping,blackmail,murder,serial killer,missing person,cybercrime,based on tv series,ice', TRUE);
CALL create_keyword_set('Call Me Chihiro', 'parent child relationship,high school,slice of life,loneliness,based on manga,ex prostitute,bento', TRUE);
CALL create_keyword_set('Sayonara, Girls', 'high school,school,high school student,japanese high school,japanese high school girl,girl,high school students,graduation ceremony', TRUE);
CALL create_keyword_set('Jesus Revolution', 'hippie,1970s,based on true story,aftercreditsstinger,southern california', TRUE);
CALL create_keyword_set('Lie with Me', 'lgbt,distillery,cognac,young lovers,gay theme,gay', TRUE);
CALL create_keyword_set('Cocaine Bear', 'cocaine,georgia,animal attack,based on true story,rampage,duringcreditsstinger,woman director,black bear,apex predator', TRUE);
CALL create_keyword_set('Sommore: Queen Chandelier', 'stand-up comedy,stand-up', TRUE);
CALL create_keyword_set('Under His Influence', 'forbidden love,inmate,social media influencer', TRUE);
CALL create_keyword_set('Return of the Demojordan', 'monster,chase,barn,forest', TRUE);
CALL create_keyword_set('It’s a Date', 'racing,lgbt,kyiv, ukraine,claude lelouch', TRUE);
CALL create_keyword_set('Broken People', 'new york city,small town,classical music,romantic comedy,romance,retro,pop music,mental health,nostalgic,mumblecore,ernest hemingway,music,indie', TRUE);
CALL create_keyword_set('Green Night', 'lesbian sex,lgbt,lesbian', TRUE);
CALL create_keyword_set('Aagantuk', 'kidnapping,sadism,socialized psychopath', TRUE);
CALL create_keyword_set('Rampage Electra', 'prison,psychiatric ward,perth, australia,fremantle', TRUE);
CALL create_keyword_set('My Year of Dicks', 'friendship,houston,coming of age,teenage girl,sexual awakening,sex comedy,woman director,virginity,1990s,short film,sex', TRUE);
CALL create_keyword_set('Free to a Bad Home', 'halloween party,break in,horror anthology', TRUE);
CALL create_keyword_set('The Integrity of Joseph Chambers', 'alabama,campsite,police chief,insurance salesman,truck,woods,rifle,deer hunting,family man', TRUE);